// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: rokid-openvoice-websocket/protobuf/common/auth.proto

package common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AuthErrorCode int32

const (
	AuthErrorCode_SUCCESS     AuthErrorCode = 0
	AuthErrorCode_AUTH_FAILED AuthErrorCode = 1
)

// Enum value maps for AuthErrorCode.
var (
	AuthErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "AUTH_FAILED",
	}
	AuthErrorCode_value = map[string]int32{
		"SUCCESS":     0,
		"AUTH_FAILED": 1,
	}
)

func (x AuthErrorCode) Enum() *AuthErrorCode {
	p := new(AuthErrorCode)
	*p = x
	return p
}

func (x AuthErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rokid_openvoice_websocket_protobuf_common_auth_proto_enumTypes[0].Descriptor()
}

func (AuthErrorCode) Type() protoreflect.EnumType {
	return &file_rokid_openvoice_websocket_protobuf_common_auth_proto_enumTypes[0]
}

func (x AuthErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AuthErrorCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AuthErrorCode(num)
	return nil
}

// Deprecated: Use AuthErrorCode.Descriptor instead.
func (AuthErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	DeviceTypeId *string `protobuf:"bytes,2,req,name=device_type_id,json=deviceTypeId" json:"device_type_id,omitempty"`
	DeviceId     *string `protobuf:"bytes,3,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Service      *string `protobuf:"bytes,4,req,name=service" json:"service,omitempty"`
	Version      *string `protobuf:"bytes,5,req,name=version" json:"version,omitempty"`
	Timestamp    *string `protobuf:"bytes,6,req,name=timestamp" json:"timestamp,omitempty"`
	Sign         *string `protobuf:"bytes,7,req,name=sign" json:"sign,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *AuthRequest) GetDeviceTypeId() string {
	if x != nil && x.DeviceTypeId != nil {
		return *x.DeviceTypeId
	}
	return ""
}

func (x *AuthRequest) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *AuthRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *AuthRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *AuthRequest) GetTimestamp() string {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return ""
}

func (x *AuthRequest) GetSign() string {
	if x != nil && x.Sign != nil {
		return *x.Sign
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *AuthErrorCode `protobuf:"varint,1,req,name=result,enum=rokid.open.speech.AuthErrorCode" json:"result,omitempty"`
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetResult() AuthErrorCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return AuthErrorCode_SUCCESS
}

var File_rokid_openvoice_websocket_protobuf_common_auth_proto protoreflect.FileDescriptor

var file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDesc = []byte{
	0x0a, 0x34, 0x72, 0x6f, 0x6b, 0x69, 0x64, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x2d, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x72, 0x6f, 0x6b, 0x69, 0x64, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x22, 0xc8, 0x01, 0x0a, 0x0b, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x07, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x22, 0x48, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x72, 0x6f, 0x6b, 0x69, 0x64, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x2d,
	0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x41, 0x55, 0x54, 0x48, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x42, 0x20, 0x5a,
	0x1e, 0x78, 0x6c, 0x72, 0x6f, 0x6b, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
}

var (
	file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescOnce sync.Once
	file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescData = file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDesc
)

func file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescGZIP() []byte {
	file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescOnce.Do(func() {
		file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescData)
	})
	return file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDescData
}

var file_rokid_openvoice_websocket_protobuf_common_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rokid_openvoice_websocket_protobuf_common_auth_proto_goTypes = []interface{}{
	(AuthErrorCode)(0),   // 0: rokid.open.speech.AuthErrorCode
	(*AuthRequest)(nil),  // 1: rokid.open.speech.AuthRequest
	(*AuthResponse)(nil), // 2: rokid.open.speech.AuthResponse
}
var file_rokid_openvoice_websocket_protobuf_common_auth_proto_depIdxs = []int32{
	0, // 0: rokid.open.speech.AuthResponse.result:type_name -> rokid.open.speech.AuthErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rokid_openvoice_websocket_protobuf_common_auth_proto_init() }
func file_rokid_openvoice_websocket_protobuf_common_auth_proto_init() {
	if File_rokid_openvoice_websocket_protobuf_common_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rokid_openvoice_websocket_protobuf_common_auth_proto_goTypes,
		DependencyIndexes: file_rokid_openvoice_websocket_protobuf_common_auth_proto_depIdxs,
		EnumInfos:         file_rokid_openvoice_websocket_protobuf_common_auth_proto_enumTypes,
		MessageInfos:      file_rokid_openvoice_websocket_protobuf_common_auth_proto_msgTypes,
	}.Build()
	File_rokid_openvoice_websocket_protobuf_common_auth_proto = out.File
	file_rokid_openvoice_websocket_protobuf_common_auth_proto_rawDesc = nil
	file_rokid_openvoice_websocket_protobuf_common_auth_proto_goTypes = nil
	file_rokid_openvoice_websocket_protobuf_common_auth_proto_depIdxs = nil
}
