// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: speech_types.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SpeechErrorCode int32

const (
	SpeechErrorCode_SUCCESS           SpeechErrorCode = 0
	SpeechErrorCode_UNAUTHENTICATED   SpeechErrorCode = 2
	SpeechErrorCode_CONNECTION_EXCEED SpeechErrorCode = 3
	SpeechErrorCode_RESOURCE_EXHASTED SpeechErrorCode = 4
	SpeechErrorCode_BUSY              SpeechErrorCode = 5
	SpeechErrorCode_INTERNAL          SpeechErrorCode = 6
	SpeechErrorCode_VAD_TIMEOUT       SpeechErrorCode = 7
	SpeechErrorCode_NLP_EMPTY         SpeechErrorCode = 8
)

// Enum value maps for SpeechErrorCode.
var (
	SpeechErrorCode_name = map[int32]string{
		0: "SUCCESS",
		2: "UNAUTHENTICATED",
		3: "CONNECTION_EXCEED",
		4: "RESOURCE_EXHASTED",
		5: "BUSY",
		6: "INTERNAL",
		7: "VAD_TIMEOUT",
		8: "NLP_EMPTY",
	}
	SpeechErrorCode_value = map[string]int32{
		"SUCCESS":           0,
		"UNAUTHENTICATED":   2,
		"CONNECTION_EXCEED": 3,
		"RESOURCE_EXHASTED": 4,
		"BUSY":              5,
		"INTERNAL":          6,
		"VAD_TIMEOUT":       7,
		"NLP_EMPTY":         8,
	}
)

func (x SpeechErrorCode) Enum() *SpeechErrorCode {
	p := new(SpeechErrorCode)
	*p = x
	return p
}

func (x SpeechErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpeechErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_speech_types_proto_enumTypes[0].Descriptor()
}

func (SpeechErrorCode) Type() protoreflect.EnumType {
	return &file_speech_types_proto_enumTypes[0]
}

func (x SpeechErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SpeechErrorCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SpeechErrorCode(num)
	return nil
}

// Deprecated: Use SpeechErrorCode.Descriptor instead.
func (SpeechErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_speech_types_proto_rawDescGZIP(), []int{0}
}

type ReqType int32

const (
	ReqType_START   ReqType = 0
	ReqType_VOICE   ReqType = 1
	ReqType_END     ReqType = 2
	ReqType_TEXT    ReqType = 3
	ReqType_ONESHOT ReqType = 4
)

// Enum value maps for ReqType.
var (
	ReqType_name = map[int32]string{
		0: "START",
		1: "VOICE",
		2: "END",
		3: "TEXT",
		4: "ONESHOT",
	}
	ReqType_value = map[string]int32{
		"START":   0,
		"VOICE":   1,
		"END":     2,
		"TEXT":    3,
		"ONESHOT": 4,
	}
)

func (x ReqType) Enum() *ReqType {
	p := new(ReqType)
	*p = x
	return p
}

func (x ReqType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqType) Descriptor() protoreflect.EnumDescriptor {
	return file_speech_types_proto_enumTypes[1].Descriptor()
}

func (ReqType) Type() protoreflect.EnumType {
	return &file_speech_types_proto_enumTypes[1]
}

func (x ReqType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ReqType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ReqType(num)
	return nil
}

// Deprecated: Use ReqType.Descriptor instead.
func (ReqType) EnumDescriptor() ([]byte, []int) {
	return file_speech_types_proto_rawDescGZIP(), []int{1}
}

type Codec int32

const (
	Codec_PCM   Codec = 0
	Codec_OPU   Codec = 1
	Codec_OPU2  Codec = 2
	Codec_OPUS  Codec = 3
	Codec_AMRNB Codec = 4
	Codec_AMRWB Codec = 5
	Codec_PCM8K Codec = 6
)

// Enum value maps for Codec.
var (
	Codec_name = map[int32]string{
		0: "PCM",
		1: "OPU",
		2: "OPU2",
		3: "OPUS",
		4: "AMRNB",
		5: "AMRWB",
		6: "PCM8K",
	}
	Codec_value = map[string]int32{
		"PCM":   0,
		"OPU":   1,
		"OPU2":  2,
		"OPUS":  3,
		"AMRNB": 4,
		"AMRWB": 5,
		"PCM8K": 6,
	}
)

func (x Codec) Enum() *Codec {
	p := new(Codec)
	*p = x
	return p
}

func (x Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_speech_types_proto_enumTypes[2].Descriptor()
}

func (Codec) Type() protoreflect.EnumType {
	return &file_speech_types_proto_enumTypes[2]
}

func (x Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Codec) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Codec(num)
	return nil
}

// Deprecated: Use Codec.Descriptor instead.
func (Codec) EnumDescriptor() ([]byte, []int) {
	return file_speech_types_proto_rawDescGZIP(), []int{2}
}

type PingPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId *int32 `protobuf:"varint,1,req,name=req_id,json=reqId" json:"req_id,omitempty"`
	// timepoint of now
	NowTp *uint64 `protobuf:"varint,2,req,name=now_tp,json=nowTp" json:"now_tp,omitempty"`
	// timepoint of request send
	ReqTp *uint64 `protobuf:"varint,3,req,name=req_tp,json=reqTp" json:"req_tp,omitempty"`
	// timepoint of response recv
	RespTp *uint64 `protobuf:"varint,4,req,name=resp_tp,json=respTp" json:"resp_tp,omitempty"`
}

func (x *PingPayload) Reset() {
	*x = PingPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speech_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPayload) ProtoMessage() {}

func (x *PingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_speech_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPayload.ProtoReflect.Descriptor instead.
func (*PingPayload) Descriptor() ([]byte, []int) {
	return file_speech_types_proto_rawDescGZIP(), []int{0}
}

func (x *PingPayload) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *PingPayload) GetNowTp() uint64 {
	if x != nil && x.NowTp != nil {
		return *x.NowTp
	}
	return 0
}

func (x *PingPayload) GetReqTp() uint64 {
	if x != nil && x.ReqTp != nil {
		return *x.ReqTp
	}
	return 0
}

func (x *PingPayload) GetRespTp() uint64 {
	if x != nil && x.RespTp != nil {
		return *x.RespTp
	}
	return 0
}

var File_speech_types_proto protoreflect.FileDescriptor

var file_speech_types_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x72, 0x6f, 0x6b, 0x69, 0x64, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x2e, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x22, 0x6b, 0x0a, 0x0b, 0x50, 0x69,
	0x6e, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x77, 0x5f, 0x74, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04,
	0x52, 0x05, 0x6e, 0x6f, 0x77, 0x54, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x74,
	0x70, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x72, 0x65, 0x71, 0x54, 0x70, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x74, 0x70, 0x18, 0x04, 0x20, 0x02, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x70, 0x54, 0x70, 0x2a, 0x99, 0x01, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x65,
	0x63, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55,
	0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x15, 0x0a,
	0x11, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x58, 0x43, 0x45,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45,
	0x5f, 0x45, 0x58, 0x48, 0x41, 0x53, 0x54, 0x45, 0x44, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x42,
	0x55, 0x53, 0x59, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x56, 0x41, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f,
	0x55, 0x54, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4c, 0x50, 0x5f, 0x45, 0x4d, 0x50, 0x54,
	0x59, 0x10, 0x08, 0x2a, 0x3f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x4f, 0x49,
	0x43, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x45, 0x53, 0x48,
	0x4f, 0x54, 0x10, 0x04, 0x2a, 0x4e, 0x0a, 0x05, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x43, 0x4d, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x50, 0x55, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x4f, 0x50, 0x55, 0x32, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x55,
	0x53, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4d, 0x52, 0x4e, 0x42, 0x10, 0x04, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x4d, 0x52, 0x57, 0x42, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x43, 0x4d,
	0x38, 0x4b, 0x10, 0x06, 0x42, 0x1f, 0x5a, 0x1d, 0x78, 0x6c, 0x72, 0x6f, 0x6b, 0x69, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31,
}

var (
	file_speech_types_proto_rawDescOnce sync.Once
	file_speech_types_proto_rawDescData = file_speech_types_proto_rawDesc
)

func file_speech_types_proto_rawDescGZIP() []byte {
	file_speech_types_proto_rawDescOnce.Do(func() {
		file_speech_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_speech_types_proto_rawDescData)
	})
	return file_speech_types_proto_rawDescData
}

var file_speech_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_speech_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_speech_types_proto_goTypes = []interface{}{
	(SpeechErrorCode)(0), // 0: rokid.open.speech.v1.SpeechErrorCode
	(ReqType)(0),         // 1: rokid.open.speech.v1.ReqType
	(Codec)(0),           // 2: rokid.open.speech.v1.Codec
	(*PingPayload)(nil),  // 3: rokid.open.speech.v1.PingPayload
}
var file_speech_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_speech_types_proto_init() }
func file_speech_types_proto_init() {
	if File_speech_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_speech_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_speech_types_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_speech_types_proto_goTypes,
		DependencyIndexes: file_speech_types_proto_depIdxs,
		EnumInfos:         file_speech_types_proto_enumTypes,
		MessageInfos:      file_speech_types_proto_msgTypes,
	}.Build()
	File_speech_types_proto = out.File
	file_speech_types_proto_rawDesc = nil
	file_speech_types_proto_goTypes = nil
	file_speech_types_proto_depIdxs = nil
}
