# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import classify_pb2 as classify__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ClassifyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntentRecognize = channel.unary_unary(
                '/nlu.v2.Classify/IntentRecognize',
                request_serializer=classify__pb2.NluRequest.SerializeToString,
                response_deserializer=classify__pb2.NluResponse.FromString,
                )
        self.GetNluVersion = channel.unary_unary(
                '/nlu.v2.Classify/GetNluVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=classify__pb2.VersionResponse.FromString,
                )


class ClassifyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IntentRecognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNluVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntentRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.IntentRecognize,
                    request_deserializer=classify__pb2.NluRequest.FromString,
                    response_serializer=classify__pb2.NluResponse.SerializeToString,
            ),
            'GetNluVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNluVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=classify__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlu.v2.Classify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Classify(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IntentRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlu.v2.Classify/IntentRecognize',
            classify__pb2.NluRequest.SerializeToString,
            classify__pb2.NluResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNluVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlu.v2.Classify/GetNluVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            classify__pb2.VersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
