# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tner.proto\x12\napi.ner.v1\x1a\x1bgoogle/protobuf/empty.proto\"O\n\x06NerReq\x12\x1a\n\x08trace_id\x18\x01 \x01(\tR\x08trace_id\x12\x1a\n\x08\x61gent_id\x18\x02 \x01(\x12R\x08\x61gent_id\x12\r\n\x05query\x18\x03 \x01(\t\"c\n\x06\x45ntity\x12\x13\n\x0b\x65ntity_type\x18\x01 \x01(\t\x12\x14\n\x0c\x65ntity_value\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x05\x12\x0e\n\x06length\x18\x05 \x01(\x05\"U\n\tNerResult\x12$\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x12.api.ner.v1.Entity\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\tcost_time\x18\x03 \x01(\x03\"`\n\x06NerRes\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\'\n\x08metadata\x18\x04 \x01(\x0b\x32\x15.api.ner.v1.NerResult\"\x08\n\x06VerReq\"\x18\n\x06VerRsp\x12\x0e\n\x06VerRsp\x18\x01 \x01(\t2\x80\x01\n\rCloudMindsNer\x12\x33\n\x07NerCall\x12\x12.api.ner.v1.NerReq\x1a\x12.api.ner.v1.NerRes\"\x00\x12:\n\nGetVersion\x12\x16.google.protobuf.Empty\x1a\x12.api.ner.v1.VerRsp\"\x00\x42,\n\napi.ner.v1P\x01Z\x1cnlp-ner-server/api/ner/v1;v1b\x06proto3')



_NERREQ = DESCRIPTOR.message_types_by_name['NerReq']
_ENTITY = DESCRIPTOR.message_types_by_name['Entity']
_NERRESULT = DESCRIPTOR.message_types_by_name['NerResult']
_NERRES = DESCRIPTOR.message_types_by_name['NerRes']
_VERREQ = DESCRIPTOR.message_types_by_name['VerReq']
_VERRSP = DESCRIPTOR.message_types_by_name['VerRsp']
NerReq = _reflection.GeneratedProtocolMessageType('NerReq', (_message.Message,), {
  'DESCRIPTOR' : _NERREQ,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:api.ner.v1.NerReq)
  })
_sym_db.RegisterMessage(NerReq)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:api.ner.v1.Entity)
  })
_sym_db.RegisterMessage(Entity)

NerResult = _reflection.GeneratedProtocolMessageType('NerResult', (_message.Message,), {
  'DESCRIPTOR' : _NERRESULT,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:api.ner.v1.NerResult)
  })
_sym_db.RegisterMessage(NerResult)

NerRes = _reflection.GeneratedProtocolMessageType('NerRes', (_message.Message,), {
  'DESCRIPTOR' : _NERRES,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:api.ner.v1.NerRes)
  })
_sym_db.RegisterMessage(NerRes)

VerReq = _reflection.GeneratedProtocolMessageType('VerReq', (_message.Message,), {
  'DESCRIPTOR' : _VERREQ,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:api.ner.v1.VerReq)
  })
_sym_db.RegisterMessage(VerReq)

VerRsp = _reflection.GeneratedProtocolMessageType('VerRsp', (_message.Message,), {
  'DESCRIPTOR' : _VERRSP,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:api.ner.v1.VerRsp)
  })
_sym_db.RegisterMessage(VerRsp)

_CLOUDMINDSNER = DESCRIPTOR.services_by_name['CloudMindsNer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\napi.ner.v1P\001Z\034nlp-ner-server/api/ner/v1;v1'
  _NERREQ._serialized_start=54
  _NERREQ._serialized_end=133
  _ENTITY._serialized_start=135
  _ENTITY._serialized_end=234
  _NERRESULT._serialized_start=236
  _NERRESULT._serialized_end=321
  _NERRES._serialized_start=323
  _NERRES._serialized_end=419
  _VERREQ._serialized_start=421
  _VERREQ._serialized_end=429
  _VERRSP._serialized_start=431
  _VERRSP._serialized_end=455
  _CLOUDMINDSNER._serialized_start=458
  _CLOUDMINDSNER._serialized_end=586
# @@protoc_insertion_point(module_scope)
