# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import qqsim_pb2 as qqsim__pb2


class QqsimServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CmQqSimSimilar = channel.unary_unary(
                '/qqsim.v1.QqsimService/CmQqSimSimilar',
                request_serializer=qqsim__pb2.CmQsimSimilarRequest.SerializeToString,
                response_deserializer=qqsim__pb2.CmQsimSimilarResponse.FromString,
                )
        self.CmQqSimSentenceEncode = channel.unary_unary(
                '/qqsim.v1.QqsimService/CmQqSimSentenceEncode',
                request_serializer=qqsim__pb2.CmQqSimSentenceRequest.SerializeToString,
                response_deserializer=qqsim__pb2.CmQqSimSentenceResponse.FromString,
                )
        self.GetQqsimVersion = channel.unary_unary(
                '/qqsim.v1.QqsimService/GetQqsimVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=qqsim__pb2.VersionResponse.FromString,
                )


class QqsimServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CmQqSimSimilar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CmQqSimSentenceEncode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQqsimVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QqsimServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CmQqSimSimilar': grpc.unary_unary_rpc_method_handler(
                    servicer.CmQqSimSimilar,
                    request_deserializer=qqsim__pb2.CmQsimSimilarRequest.FromString,
                    response_serializer=qqsim__pb2.CmQsimSimilarResponse.SerializeToString,
            ),
            'CmQqSimSentenceEncode': grpc.unary_unary_rpc_method_handler(
                    servicer.CmQqSimSentenceEncode,
                    request_deserializer=qqsim__pb2.CmQqSimSentenceRequest.FromString,
                    response_serializer=qqsim__pb2.CmQqSimSentenceResponse.SerializeToString,
            ),
            'GetQqsimVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQqsimVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=qqsim__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qqsim.v1.QqsimService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QqsimService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CmQqSimSimilar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qqsim.v1.QqsimService/CmQqSimSimilar',
            qqsim__pb2.CmQsimSimilarRequest.SerializeToString,
            qqsim__pb2.CmQsimSimilarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CmQqSimSentenceEncode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qqsim.v1.QqsimService/CmQqSimSentenceEncode',
            qqsim__pb2.CmQqSimSentenceRequest.SerializeToString,
            qqsim__pb2.CmQqSimSentenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQqsimVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qqsim.v1.QqsimService/GetQqsimVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            qqsim__pb2.VersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
